In [29]:
#1. Write a function that takes a string and returns a dictionary with counts of: vowels, consonants, digits, special characters.
st = "It's 4th day of the python questions!"

def cou(string):
    string = string.lower()
    vowels_count = consonant_count = digit_count = special_count = 0
    vowels = 'aeiou'
    for i in string:
        if i in vowels:
            vowels_count += 1
        elif i.isdigit():
            digit_count += 1
        elif i.isalpha():
            consonant_count += 1
        elif not i.isspace():
            special_count += 1
    return {'Vowles':{vowels_count} ,'Consonants':{consonant_count}, 'Digits':{digit_count},'Special Characters':{special_count}}



In [30]:
cou(st)

{'Vowles': {9}, 'Consonants': {19}, 'Digits': {1}, 'Special Characters': {2}}

In [31]:
#2. Create a 1D NumPy array of 20 random integers between 1 and 100.
# Replace all even numbers with -1.

import numpy as np
arr = np.random.randint(1,100,20)
arr[arr%2 == 0] = -1
arr

array([ 9, 69, -1, -1, 39, -1, -1, 71, 51, -1, -1, 77, 65, 57, 99, -1, -1,
       -1, 65, 23])

In [32]:
#3.x = (1,2,3)
#x[0] = 10  #spot the error

x is a tuple and tuple are immutable. We cannot change it after it has been created.

In [33]:
#4. Given two lists:
# list1 = [1,2,3,4,5]
# list2 = [4,5,6,7,8]
# Find:
# elements common in both
# elements only in list1
# union of both lists

common_list = list(set([1,2,3,4,5]) & set([4,5,6,7,8]))
only_in_list1 = list(set([1,2,3,4,5]) - set([4,5,6,7,8]))
union_list = list(set([1,2,3,4,5]) | set([4,5,6,7,8]))

In [34]:
common_list, only_in_list1, union_list

([4, 5], [1, 2, 3], [1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
#5. Write a function fibonacci(n) that returns a list of the first n Fibonacci numbers.

def fibonacci(n):
    fib_list = [0,1]
    a,b = 0,1
    for i in range(2,n):
        c = a + b
        fib_list.append(c)
        a, b = b, c
    return fib_list


In [36]:
fibonacci(10)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [37]:
#6.Given:
words = ["data", "science", "is", "fun"]
# Create a list of the lengths of each word using a list comprehension.
# (Expected: [4, 7, 2, 3])

len_list = [len(word) for word in words]
len_list

[4, 7, 2, 3]

In [38]:
#7.You are given:
import pandas as pd
df = pd.DataFrame({
    'Name': ['A', 'B', 'C', 'D', 'E'],
    'Age': [23, 35, 29, 40, 22],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})
# Write code to filter only the rows where:
# Age is greater than 25, and
# Department is IT.
df[(df['Age']>25) & (df['Department'] == 'IT')]

Name  Age Department
1    B   35         IT
3    D   40         IT

In [39]:
#8. Create a 3×3 NumPy matrix with values from 1 to 9.
# Find its transpose.
# Calculate the sum of each row.
# Multiply it element-wise with another 3×3 matrix of ones.

arr = np.arange(1,10).reshape(3,3)
transpose1 = arr.T
row_sum = arr.sum(axis=1)
mat1 =np.ones((3,3))
mul = arr*mat1
transpose1, row_sum, mul

(array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]),
 array([ 6, 15, 24]),
 array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]))